import { OnyItem } from "./ony_interfaces";

export const onyItems: OnyItem[] = [



  {
    id: 'chaise_plastique',
    categorie: 'Chaise',
    subCategorie: '',
    nom: 'plastique',
    prix: 250,
    description: 'La chaise en plastique est une option pratique et économique pour les organisateurs d\'événements qui cherchent des sièges résistants, confortables et faciles à transporter.',
    image: ['chaise_plastique_blanche_1', 'chaise_plastique_blanche_2', 'chaise_plastique_blanche_3'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'chaise_vip_mousse',
    categorie: 'Chaise',
    subCategorie: 'vip',
    nom: 'mousse',
    prix: 1500,
    description: 'La chaise VIP en couleur rouge est un siège haut de gamme conçu pour les événements de prestige tels que les mariages, les galas, les cérémonies ou les conférences.',
    image: ['chaise_vip_mousse_rouge_1', 'chaise_vip_mousse_rouge_2', 'chaise_vip_mousse_rouge_3', 'chaise_vip_mousse_rouge_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'chaise_vip_napoleon',
    categorie: 'Chaise',
    subCategorie: 'vip',
    nom: 'napoléon',
    prix: 2500,
    description: 'La chaise VIP Napoléon est un siège haut de gamme conçu pour apporter une touche de sophistication et de raffinement à tout événement.',
    image: ['chaise_vip_napoleon_1', 'chaise_vip_napoleon_2'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'chaise_pupitre_conference',
    categorie: 'Chaise',
    subCategorie: 'pupitre',
    nom: 'conférence',
    prix: 25000,
    description: 'Le pupitre est une outil conçue pour être utilisée comme une plate-forme d\'orateur pour les événements professionnels tels que les discours, les présentations et les conférences.',
    image: ['pupitre_1', 'pupitre_2', 'pupitre_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'chaise_fauteuil_simple',
    categorie: 'Chaise',
    subCategorie: 'fauteuil',
    nom: 'simple',
    prix: 20000,
    description: 'Cette chaise est un investissement.',
    image: ['fauteuil_tradition_simple_1', 'fauteuil_moderne_simple_1', 'fauteuil_moderne_simple_3', 'fauteuil_moderne_simple_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'chaise_fauteuil_marie',
    categorie: 'Chaise',
    subCategorie: 'fauteuil',
    nom: 'marié',
    prix: 30000,
    description: 'Judicieux pour ceux qui recherchent un siège de qualité supérieure pour leurs événements professionnels.',
    image: ['fauteuil_tradition_double_4', 'fauteuil_tradition_double_2', 'fauteuil_tradition_double_3'],
    quantite: 1,
    unite: 'piece',
  },




  {
    id: 'couvert_assiette_aperitif',
    categorie: 'Couvert',
    subCategorie: 'assiette',
    nom: 'apéritif',
    prix: 250,
    description: 'Un choix de design multiple. Prix abordable.',
    image: ['verre_collection'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_simple_sch_m_112',
    categorie: 'Couvert',
    subCategorie: 'simple',
    nom: 'SCH-M-112',
    prix: 1000,
    description: 'Couverts simples en acier inoxydable avec un design épuré et classique.',
    image: ['couvert_simple_churchill_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_simple_c_s_i_112',
    categorie: 'Couvert',
    subCategorie: 'simple',
    nom: 'C S I - 112',
    prix: 850,
    description: 'Prix abordable.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_basic_bl_c_112',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'basic BL-C-112',
    prix: 1000,
    description: 'Couverts basiques en acier inoxydable avec un design simple mais élégant. Parfait pour une utilisation quotidienne.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_classic_cch_m_223',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'classic CCH-M-223',
    prix: 1300,
    description: 'Couverts classiques en acier inoxydable avec un design sophistiqué. Parfait pour les occasions spéciales.',
    image: ['couvert_complet_churchill'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_chic_cl_c_223',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'chic CL-C-223',
    prix: 1500,
    description: 'Couverts chic en acier inoxydable avec un design élégant et moderne.',
    image: ['couvert_complet_plate_ronde_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_ultra_uch_m_233',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'ultra UCH-M-233',
    prix: 1500,
    description: 'Pour les événements haut de gamme.',
    image: ['couvert_complet_plate_carree_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_elite_el_c_233',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'elite EL-C-233',
    prix: 1800,
    description: 'Couverts élites en acier inoxydable avec un design raffiné et haut de gamme. Parfait pour les événements de prestige.',
    image: ['couvert_complet_carre_feuille'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_vip_vch_m_333',
    categorie: 'Couvert',
    subCategorie: 'vip',
    nom: 'VCH-M-333',
    prix: 2000,
    description: 'Couverts VIP en acier inoxydable avec un design élégant et exclusif.',
    image: ['couvert_complet_churchill'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_vip_vl_c_333',
    categorie: 'Couvert',
    subCategorie: 'vip',
    nom: 'VL-C-333',
    prix: 2300,
    description: 'Prix encore plus élevé pour une expérience culinaire de prestige.',
    image: ['couvert_complet_louis_xv_3', 'couvert_complet_louis_xv_2', 'couvert_complet_louis_xv_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_set_apero_entremets_lunch',
    categorie: 'Couvert',
    subCategorie: 'set > apero',
    nom: 'Entremets / Lunch',
    prix: 350,
    description: 'Set de couverts pour apéritif comprenant des fourchettes, couteaux et cuillères à soupe de différentes tailles.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_set_apero_le_11',
    categorie: 'Couvert',
    subCategorie: 'set > apero',
    nom: 'LE - 11',
    prix: 400,
    description: 'Set de couverts pour apéritif comprenant des fourchettes, couteaux et cuillères à soupe de différentes tailles.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_set_cocktail_dinatoire',
    categorie: 'Couvert',
    subCategorie: 'set',
    nom: 'cocktail dinatoire',
    prix: 700,
    description: 'Parfait pour les événements cocktail.',
    image: ['verre_Martini'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_set_entre_mets',
    categorie: 'Couvert',
    subCategorie: 'set',
    nom: 'entre-mets',
    prix: 350,
    description: 'Set de couverts pour entrée comprenant une fourchette et un couteau. Prix abordable pour les événements formels.',
    image: ['couteau_fourchette_cuiillere_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_tasse_universelle',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'tasse universelle',
    prix: 250,
    description: 'Tasse universelle en porcelaine avec un design simple et élégant. Parfait pour le thé et le café.',
    image: ['os1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'couvert_divers_verres_apero',
    categorie: 'Couvert',
    subCategorie: '',
    nom: 'divers verres apero',
    prix: 250,
    description: 'Ensemble de verres à apéritif comprenant des verres à vin et des verres à champagne. Parfait pour les événements cocktails.',
    image: ['verre_collection'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_chaise_noeud_bandeau',
    categorie: 'Habillage',
    subCategorie: 'chaise > noeud',
    nom: 'bandeau',
    prix: 500,
    description: 'Cet habillage pour chaise comprend un bandeau en tissu avec un nœud décoratif pour ajouter une touche élégante à votre événement',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_chaise_noeud_ruban',
    categorie: 'Habillage',
    subCategorie: 'chaise > noeud',
    nom: 'ruban',
    prix: 1000,
    description: 'Avec un prix de 1000, il offre une belle finition à votre événement à un coût raisonnable.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_chaise_housse_lycra_simple',
    categorie: 'Habillage',
    subCategorie: 'chaise > Housse lycra',
    nom: 'simple',
    prix: 1000,
    description: 'Housse lycra est une housse de chaise en tissu lycra élastique.',
    image: ['housse_lycra_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_chaise_housse_lycra_vip',
    categorie: 'Habillage',
    subCategorie: 'chaise > Housse lycra',
    nom: 'vip',
    prix: 1000,
    description: 'Un look chic et élégant.',
    image: ['housse_lycra_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_nappe_simple_r10',
    categorie: 'Habillage',
    subCategorie: 'nappe',
    nom: 'simple r10',
    prix: 3500,
    description: 'Une nappe simple conçue pour couvrir parfaitement la table, la protéger des rayures et des taches.',
    image: ['nappe_table_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_nappe_impression_r8',
    categorie: 'Habillage',
    subCategorie: 'nappe > impression',
    nom: 'r8',
    prix: 3500,
    description: 'La nappe en impression ronde de 8 personnes est un accessoire parfait pour habiller votre table de manière élégante et conviviale.',
    image: ['nappe_table_carreau_polyester'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_nappe_impression_r10',
    categorie: 'Habillage',
    subCategorie: 'nappe > impression',
    nom: 'r10',
    prix: 5000,
    description: 'Cette nappe d\'impression r10 est disponible dans une variété de motifs et de couleurs pour correspondre à n\'importe quel thème ou décoration d\'événement.',
    image: ['nappe_table_impression_eclat'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_nappe_surnappe',
    categorie: 'Habillage',
    subCategorie: 'nappe',
    nom: 'surnappe',
    prix: 2500,
    description: 'Une surnappe est une pièce de tissu décorative qui est souvent placée sur une nappe pour ajouter une touche supplémentaire de couleur ou de texture à une table.',
    image: ['nappe_surnappe_table'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_pm_gateau_nid_impression',
    categorie: 'Habillage',
    subCategorie: 'buffet > pm gateau nid',
    nom: 'impression',
    prix: 6500,
    description: 'Cette habillage pour buffet de taille petite/moyenne est nommé pm gateau nid. Il est imprimé avec un motif particulier et son prix est de 6500.',
    image: ['jupon_blanc_2'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_pm_gateau_nid_blanc',
    categorie: 'Habillage',
    subCategorie: 'buffet > pm gateau nid',
    nom: 'blanc',
    prix: 8000,
    description: 'Cette housse d\'habillage de buffet pm gateau nid en blanc est l\'accessoire parfait pour sublimer votre buffet et ajouter une touche d\'élégance à votre événement.',
    image: ['jupon_blanc_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_mm_impression',
    categorie: 'Habillage',
    subCategorie: 'buffet > mm',
    nom: 'jupon_bleu',
    prix: 12000,
    description: 'Cette housse d\'habillage pour buffet de taille moyenne est idéale pour donner une touche personnalisée à votre événement.',
    image: ['jupon_blanc_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_mm_blanc',
    categorie: 'Habillage',
    subCategorie: 'buffet > mm',
    nom: 'blanc',
    prix: 15000,
    description: 'L\'habillage de buffet mm en blanc est parfait pour donner une touche d\'élégance et de raffinement à votre événement.',
    image: ['jupon_blanc'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_gm_impression',
    categorie: 'Habillage',
    subCategorie: 'buffet > gm',
    nom: 'impression',
    prix: 17500,
    description: 'Housse de buffet pour les grandes occasions, avec une impression personnalisée qui saura attirer tous les regards. Prix raisonnable pour une ambiance unique.',
    image: ['jupon_blanc_2'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_gm_blanc',
    categorie: 'Habillage',
    subCategorie: 'buffet > gm',
    nom: 'blanc',
    prix: 22000,
    description: 'Qualité supérieure pour un prix qui en vaut la peine.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_buffet_table_honneur_blanc',
    categorie: 'Habillage',
    subCategorie: 'buffet > table honneur',
    nom: 'blanc',
    prix: 35000,
    description: 'La table d\'honneur blanche est la pièce maîtresse de toute réception digne de ce nom.',
    image: ['jupon_blanc_2'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'habillage_drapage_chapiteau',
    categorie: 'Habillage',
    subCategorie: '',
    nom: 'drapage chapiteau',
    prix: 35000,
    description: 'Cette option de \'Drapage Chapiteau\' pour l\'habillage de votre buffet est parfaite pour les événements en extérieur ou dans une tente.',
    image: ['fauteuil_tradition_double_3'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_chaffing_dish_complet_rond',
    categorie: 'Plateau',
    subCategorie: 'chaffing dish complet',
    nom: 'rond',
    prix: 3500,
    description: 'Disponible en forme ronde, ovale et rectangulaire.',
    image: ['chaffing_dish_rond_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_chaffing_dish_complet_oval',
    categorie: 'Plateau',
    subCategorie: 'chaffing dish complet',
    nom: 'oval',
    prix: 4000,
    description: 'Disponible en forme ronde, ovale et rectangulaire.',
    image: ['chaffing_dish_oval_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_chaffing_dish_complet_rect',
    categorie: 'Plateau',
    subCategorie: 'chaffing dish complet',
    nom: 'rect',
    prix: 4000,
    description: 'Disponible en forme ronde, ovale et rectangulaire.',
    image: ['chaffing_dish_rectangle_4'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_grille_support_cocktail_dish',
    categorie: 'Plateau',
    subCategorie: '',
    nom: 'grille support cocktail dish',
    prix: 2000,
    description: 'Un support de grille pour tenir les plats de cocktail chauds. Idéal pour les événements de cocktail.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_dish',
    categorie: 'Plateau',
    subCategorie: '',
    nom: 'dish',
    prix: 3000,
    description: 'Un grand plat de service pour les plats principaux lors des repas formels.',
    image: ['plateau'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_hors_d_oeuvre_l60',
    categorie: 'Plateau',
    subCategorie: 'hors-d\'oeuvre',
    nom: 'L60',
    prix: 2500,
    description: 'Un plateau de service pour les hors-d\'oeuvre. Disponible en deux tailles : L60 et L80.',
    image: ['plateau_couson_oval'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_hors_d_oeuvre_l80',
    categorie: 'Plateau',
    subCategorie: 'hors-d\'oeuvre',
    nom: 'L80',
    prix: 4000,
    description: 'Un plateau de service pour les hors-d\'oeuvre. Disponible en deux tailles : L60 et L80.',
    image: ['plateau_guy_degrenne'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_mechoui',
    categorie: 'Plateau',
    subCategorie: '',
    nom: 'méchoui',
    prix: 10000,
    description: 'Un grand plateau de service pour les méchouis.',
    image: ['plateau_rectangulaire'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_paella',
    categorie: 'Plateau',
    subCategorie: '',
    nom: 'paella',
    prix: 10000,
    description: 'Un grand plat de service pour les paellas.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'plateau_accessoires',
    categorie: 'Plateau',
    subCategorie: '',
    nom: 'accessoires',
    prix: 250,
    description: 'Divers accessoires de service pour les plats, tels que des cuillères, des pinces, etc.',
    image: ['accessoire_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_desserte_a_gateaux',
    categorie: 'Table',
    subCategorie: '',
    nom: 'desserte à gâteaux',
    prix: 15000,
    description: 'La table desserte à gâteaux est une table de service spécialement conçue pour présenter et servir des desserts lors d\'événements spéciaux tels que les mariages, les fêtes d\'anniversaire ou les événements d\'entreprise. Cette table est fabriquée à partir de matériaux de haute qualité pour garantir sa robustesse et sa durabilité. Elle est également facile à déplacer, à ranger et à nettoyer.',
    image: ['table_mange_debouti'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_demi_lune',
    categorie: 'Table',
    subCategorie: '',
    nom: 'demi-lune',
    prix: 12500,
    description: 'Une table de forme demi-circulaire, idéale pour les événements tels que les mariages, les réceptions ou les banquets. Cette table est également abordable, ce qui en fait une option idéale pour les événements de petite et moyenne taille.',
    image: [],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_ronde_r8',
    categorie: 'Table',
    subCategorie: 'ronde',
    nom: 'r8',
    prix: 4000,
    description: 'Cette table est également abordable,Ce qui en fait une option idéale pour les événements de petite et moyenne taille.',
    image: ['table_ronde_8p'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_ronde_r10_nude',
    categorie: 'Table',
    subCategorie: 'ronde > r10',
    nom: 'nude',
    prix: 5000,
    description: 'Cette table est idéale pour les événements modernes et minimalistes, où l\'accent est mis sur la simplicité et le raffinement.',
    image: ['table_ronde_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_ronde_r10_stratifiee',
    categorie: 'Table',
    subCategorie: 'ronde > r10',
    nom: 'stratifiée',
    prix: 6000,
    description: 'Légèrement plus chère que les tables rondes standard, mais la durabilité et la facilité d\'entretien offertes par le stratifié en valent la peine.',
    image: ['table_ronde_10p'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_tretaux_pm',
    categorie: 'Table',
    subCategorie: 'tretaux',
    nom: 'pm',
    prix: 2000,
    description: 'Le design à tréteaux signifie que les jambes se replient pour un rangement compact lorsqu\'elle n\'est pas utilisée.',
    image: ['nappe_table_1'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'table_tretaux_gm',
    categorie: 'Table',
    subCategorie: 'tretaux',
    nom: 'gm',
    prix: 3000,
    description: 'La table tréteaux GM est une table pratique et robuste qui convient parfaitement pour les événements de grande envergure tels que les mariages, les fêtes d\'entreprise ou les foires.',
    image: ['nappe_table_1'],
    quantite: 1,
    unite: 'piece',
  },





  {
    id: 'tente_ordinaire_6_metres_60_places',
    categorie: 'Tente',
    subCategorie: 'ordinaire',
    nom: '6 mètres (60 places)',
    prix: 30000,
    description: 'Ce produit est une tente ordinaire de 6 mètres de longueur qui peut accueillir jusqu\'à 60 personnes.',
    image: ['tente_ext'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'tente_ordinaire_8_metres_80_places',
    categorie: 'Tente',
    subCategorie: 'ordinaire',
    nom: '8 mètres (80 places)',
    prix: 35000,
    description: 'La tente ordinaire de 8 mètres de longueur, capable d\'accueillir jusqu\'à 80 personnes.Le prix de la tente est de 35000 Fcfa.',
    image: ['tente_ext'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'tente_ordinaire_12_metres_150_places',
    categorie: 'Tente',
    subCategorie: 'ordinaire',
    nom: '12 mètres (150 places)',
    prix: 50000,
    description: 'La tente est suffisamment grande pour accueillir une grande foule et offre un espace de rassemblement confortable et protégé.',
    image: ['tente_ext'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'tente_special_10m',
    categorie: 'Tente',
    subCategorie: 'special',
    nom: '10m',
    prix: 50000,
    description: 'Le prix de la tente est de 50000 Fcfa.',
    image: ['tente_special'],
    quantite: 1,
    unite: 'piece',
  },
  {
    id: 'tente_special_15m',
    categorie: 'Tente',
    subCategorie: 'special',
    nom: '15m',
    prix: 75000,
    description: 'La tente \'spécial\' de 15 mètres est un choix idéal pour les organisateurs d\'événements qui cherchent à accueillir des événements de grande envergure en plein air.',
    image: ['tente_special'],
    quantite: 1,
    unite: 'piece',
  },




  {
    id: 'service_animation_culturelle',
    categorie: 'Service',
    subCategorie: '',
    nom: 'animation culturelle',
    prix: 60000,
    description: 'Voir Catalogue...',
    image: ['service_hotesse_2'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_cuisine',
    categorie: 'Service',
    subCategorie: '',
    nom: 'cuisine',
    prix: 15000,
    description: 'Selon vos goûts et vos préférences.Voir Catalogue...',
    image: ['cuisini', 'cuisinii', 'cuisiniii', 'cuisiniv'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_decoration_espace_mariage_coutumier',
    categorie: 'Service',
    subCategorie: 'décoration espace > mariage',
    nom: 'coutumier',
    prix: 60000,
    description: 'ce service permet de personnaliser l\'espace de votre événement, que ce soit pour un mariage coutumier ou civil, selon vos goûts et vos préférences.',
    image: ['fauteuil_tradition_double_2'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_decoration_espace_mariage_civil',
    categorie: 'Service',
    subCategorie: 'décoration espace > mariage',
    nom: 'civil',
    prix: 60000,
    description: 'ce service permet de personnaliser l\'espace de votre événement, que ce soit pour un mariage coutumier ou civil, selon vos goûts et vos préférences.',
    image: ['tente_special'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_vehicules_des_maries',
    categorie: 'Service',
    subCategorie: '',
    nom: 'véhicules des mariés',
    prix: 60000,
    description: 'Propose des véhicules de location pour les mariés, afin de les transporter avec élégance et confort lors de leur mariage.',
    image: ['service_vehicule'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_personnel_hotesse',
    categorie: 'Service',
    subCategorie: 'personnel',
    nom: 'hotesse',
    prix: 20000,
    description: 'Met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: [],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_personnel_steward',
    categorie: 'Service',
    subCategorie: 'personnel',
    nom: 'steward',
    prix: 20000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: ['service_hotesse'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_personnel_nettoyage_couvert',
    categorie: 'Service',
    subCategorie: 'personnel > nettoyage',
    nom: 'couvert',
    prix: 20000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: [],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_personnel_nettoyage_rangement',
    categorie: 'Service',
    subCategorie: 'personnel > nettoyage',
    nom: 'rangement',
    prix: 20000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: [],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_media_photo',
    categorie: 'Service',
    subCategorie: 'média',
    nom: 'photo',
    prix: 50000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: ['service_photo'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_media_video',
    categorie: 'Service',
    subCategorie: 'média',
    nom: 'video',
    prix: 100000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: ['service_camera_video'],
    quantite: 1,
    unite: 'prestation',
  },
  {
    id: 'service_media_sonorisation',
    categorie: 'Service',
    subCategorie: 'média',
    nom: 'sonorisation',
    prix: 100000,
    description: 'Ce service met à disposition des hôtesses et stewards pour accueillir vos invités et les servir, ainsi que des équipes de nettoyage pour s\'occuper du rangement et du nettoyage de la salle après l\'événement.',
    image: ['service_sonorisation_2'],
    quantite: 1,
    unite: 'prestation',
  },
];