// Liste des fichiers présents dans public/images/ (sans l'extension).
// Sert à vérifier qu'un identifiant référencé dans ony_items.ts correspond
// bien à une photo existante avant de l'utiliser — évite les images cassées
// si un identifiant est mal orthographié ou que le fichier n'a pas encore
// été fourni.
export const availableProductImages = new Set<string>([
  'accessoire_1', 'accessoire_2', 'accessoire_3', 'accessoire_4', 'accessoire_5', 'accessoire_6', 'accessoire_7', 'accessoire_8',
  'assiette_churchill', 'assiette_louis_xv', 'assiette_melamime_set', 'assiette_plate_carree', 'assiette_plate_rond',
  'chaffing_dish_oval_1', 'chaffing_dish_oval_2', 'chaffing_dish_oval_3', 'chaffing_dish_oval_4',
  'chaffing_dish_rectangle_4', 'chaffing_dish_rectangle_5',
  'chaffing_dish_rond_1', 'chaffing_dish_rond_2', 'chaffing_dish_rond_3', 'chaffing_dish_rond_4', 'chaffing_dish_rond_5',
  'chaise_plastique_blanche_1', 'chaise_plastique_blanche_2', 'chaise_plastique_blanche_3',
  'chaise_vip_mousse_rouge_1', 'chaise_vip_mousse_rouge_2', 'chaise_vip_mousse_rouge_3', 'chaise_vip_mousse_rouge_4',
  'chaise_vip_napoleon_1', 'chaise_vip_napoleon_2',
  'couteau_fourchette_cuiillere_1', 'couteau_fourchette_cuiillere_2', 'couteau_fourchette_cuiillere_3', 'couteau_fourchette_cuiillere_4',
  'couvercle_sauc',
  'couvert_complet_carre_feuille', 'couvert_complet_churchill',
  'couvert_complet_louis_xv_1', 'couvert_complet_louis_xv_2', 'couvert_complet_louis_xv_3',
  'couvert_complet_plate_ronde_1', 'couvert_complet_plate_carree_1',
  'couvert_simple_churchill_1',
  'cuisini', 'cuisinii', 'cuisiniii', 'cuisiniv',
  'deco', 'decoii', 'decoiii', 'decoiv', 'decov', 'decovi',
  'fauteuil_moderne_simple_1', 'fauteuil_moderne_simple_3', 'fauteuil_moderne_simple_4',
  'fauteuil_tradition_double_2', 'fauteuil_tradition_double_3', 'fauteuil_tradition_double_4',
  'fauteuil_tradition_simple_1',
  'housse_lycra_1',
  'jupon_1', 'jupon_blanc_1', 'jupon_blanc_2', 'jupon_blanc_3', 'jupon_bleu', 'jupon_multi_fleur_afrik', 'jupon_rouge',
  'logo',
  'marmitte_presentoire_oval',
  'nappeilp', 'nappe_surnappe_table',
  'nappe_table_1', 'nappe_table_2', 'nappe_table_4', 'nappe_table_5', 'nappe_table_6',
  'nappe_table_carreau_polyester', 'nappe_table_impression_eclat', 'nappe_table_special',
  'os1', 'os2',
  'plateau', 'plateau_a_pain', 'plateau_couson_oval', 'plateau_guy_degrenne', 'plateau_rectangulaire',
  'pupitre_1', 'pupitre_2', 'pupitre_4',
  'ravier_20cm',
  'saucière innox',
  'service_camera_video', 'service_hotesse', 'service_hotesse_2', 'service_hotesse_steward',
  'service_photo', 'service_sonorisation_1', 'service_sonorisation_2',
  'service_vehicule',
  'set de table',
  'table_exterieur', 'table_mange_debout', 'table_mange_debouti',
  'table_ronde_1', 'table_ronde_10p', 'table_ronde_2', 'table_ronde_8p',
  'tente_4m', 'tente_6m', 'tente_ext', 'tente_special',
  'verre_ballon_1', 'verre_ballon_2', 'verre_ballon_3',
  'verre_collection', 'verre_coupe_de_fruit',
  'verre_droit_1', 'verre_droit_2',
  'verre_flute_1', 'verre_flute_2', 'verre_flute_3',
  'verre_imperial', 'verre_Martini',
]);